import { Module } from '@nestjs/common';
import { APP_GUARD } from '@nestjs/core';
import { JwtModule } from '@nestjs/jwt';
import { PassportModule } from '@nestjs/passport';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ApiConfigService } from '@realworld/shared/api/config';
import { Follow } from './follow.entity';
import { FollowService } from './follow.service';
import { JwtAuthGuard } from './jwt-strategy/jwt-auth.guard';
import { JwtStrategy } from './jwt-strategy/jwt.strategy';
import { RolesGuard } from './roles.guard';
import { User } from './user.entity';
import { UserService } from './user.service';

@Module({
  // This module uses the forFeature() method to define which repositories are registered in the current scope. With that in place, we can inject the UsersRepository into the UsersService
  // If you want to use the repository outside of the module which imports TypeOrmModule.forFeature, you'll need to re-export the providers generated by it. You can do this by exporting the whole module.
  imports: [
    TypeOrmModule.forFeature([User, Follow]),
    PassportModule.register({defaultStrategy: 'jwt'}),
    JwtModule.registerAsync({
      useFactory: (config: ApiConfigService) => {
        return {
          secret: config.configs.jwtSecret,
          signOptions: {expiresIn: config.configs.jwtExpiresIn || '1d'}
        }
      },
      inject: [ApiConfigService]
    })
  ],
  providers: [
    UserService,
    FollowService,
    JwtStrategy,
    {
      provide: APP_GUARD,
      useClass: JwtAuthGuard,
    },
    {
      provide: APP_GUARD,
      useClass: RolesGuard,
    },
  ],
  exports: [UserService, FollowService, JwtStrategy]
})
export class UserApiSharedModule {}
